# Generated by Django 3.0.5 on 2020-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('Biological Sciences', 'Biological Sciences'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Electrical engg. & Computer Science', 'Electrical engg. & Computer Science'), ('Earth and Environment Science', 'Earth and Environment Science'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], default='Biological Sciences', max_length=100)),
                ('internship', models.TextField(max_length=500)),
                ('experience', models.TextField(max_length=500)),
                ('non_scholastic', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
